---
version: "3.8"
services:
  server-movies:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8001:80
    networks:
      - app-network-movies
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  db-movies:
    image: postgres:13
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_DATABASE
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
    networks:
      - app-network-movies
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app-movies:
    build: .
    restart: unless-stopped
    networks:
      - app-network-movies
    volumes:
      - ./:/var/www
networks:
  app-network-movies:
    driver: bridge
volumes:
  db_data: null